### PR TITLE
testscript: don't allow negative file modes

### PR DESCRIPTION
**Pull request by twpayne**
Trivial.

### CODE REVIEW

**Comment by myitcv** [comment]
We could actually use this opportunity to refresh this method and bring it in-line with upstream:

https://github.com/golang/go/blob/881d5405402d6e8c54f83eed6216a9ed29778006/src/cmd/go/script_test.go#L456-L475

@twpayne you happy to also make those tweaks?

**Comment by twpayne** [comment]
> We could actually use this opportunity to refresh this method and bring it in-line with upstream:

Done in #104.

**Comment by mvdan** [comment]
@twpayne this now conflicts with master, after I merged #104 - is this PR still relevant? if so, please rebase it.

**Comment by twpayne** [comment]
This PR is no longer relevant - the same change was also included in #104, which has now been merged.

**Comment by mvdan** [comment]
Great! Thanks again for contributing.

**Pull request closed without merging**
