### PR TITLE
testscript: add support for Go master aka 1.18

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Review by myitcv — APPROVED** [review]
LGTM although I'll declare I'm not too familiar with the fuzzy stuff

**Review by rogpeppe — APPROVED** [review]
LGTM, thanks!

**Comment by mvdan** [comment]
@rogpeppe @myitcv test-gotip is now added. It takes about 3m, compared to just under 1m for the stable version. That is to be expected, as building from source takes between a minute and two on average hardware.

**Comment by myitcv** [comment]
Still LGTM. Thank you for going the extra mile 😄

**Pull request merged**
